version: "3"
services:
  laravel:
    tty: true
    image: bitnami/laravel:7
    container_name: laravel_container
    ports:
      - 8083:3000
    volumes:
      - ./laravel:/app
    command: >
      bash -c " composer install
      && php artisan route:list
      && php artisan key:generate
      && php artisan migrate
      && php artisan db:seed
      && php artisan serve --host=0.0.0.0 --port=3000 "
    depends_on:
      - database
      - redis
    networks:
      - servidor_network

  web:
    build:
      context: ./go
      args:
        - MODULE_NAME=goApp
    container_name: go_container
    working_dir: /go/src/${MODULE_NAME}
    volumes:
      - ./go:/go/src/${MODULE_NAME}
    ports:
      - "8090:3000"
    labels:
      traefik.backend: "web"
      traefik.frontend.rule: "PathPrefix:/"
    depends_on:
      - database
      - redis
    networks:
      - servidor_network

  database:
    image: mysql:5.7
    container_name: database_container
    environment:
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_ROOT_PASSWORD=common404"
    volumes:
      - ./mySqlBackup:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - servidor_network

  redis:
    image: redis:4.0
    container_name: redis_container
    volumes:
      - redisData:/data
    ports:
      - "6382:6379"
    networks:
      - servidor_network

  traefik:
    image: traefik:v2.0
    container_name: traefik_container
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - servidor_network

networks:
  servidor_network:

volumes:
  redisData:
